### ISSUE TITLE
k3- b版 5.0.9  中 acme 插件 填写玩参数,点击提交无反应

### ISSUE THREAD

**Issue by tanpengsccd** [MerlinRdev/softcenterarm#22]
acme版本 3.0
52f3c15ed5f331135bb400ecd9e79901

**Comment by tanpengsccd** [comment]
dnspod 和 goddaddy都试过 无反应

**Comment by tanpengsccd** [comment]
点击查看日志 也是空的.

**Comment by paldier** [comment]
https://github.com/MerlinRdev/softcenterarmng/blob/master/acme/acme.tar.gz
可以先用这个离线包
在线版本过段时间更新
