### ISSUE TITLE
K3-科学上网插件访问控制删除异常

### ISSUE THREAD

**Issue by shashou121** [MerlinRdev/softcenterarm#23]
![12](https://user-images.githubusercontent.com/33596331/79077989-d21cd680-7d37-11ea-8888-a3d15d84560c.png)

K3-科学上网插件访问控制删除异常，每次删除都会保留空数据行

**Comment by tanpengsccd** [comment]
k3 的trojan 貌似有问题.经常不能扶墙.vmess 就没问题

**Comment by mbtCoder** [comment]
same issue with owner  and Trojan do not working

**Comment by tanpengsccd** [comment]
请问，最新版已经解决了吗？
