### ISSUE TITLE
K3-B-v5.0.9  Trojan do not working in 科学上网4.2.7

### ISSUE THREAD

**Issue by mbtCoder** [MerlinRdev/softcenterarm#24]
K3 B版本 5.0.9
软件中心1.2.6
科学上网最新4.2.7
Trojan开启后无反应,无法连接外网

**Comment by mbtCoder** [comment]
24天了也没回复 也没处理, 作者用的别人的源码适配MerlinR 没调试就上架,    放弃了,入了软路由, K3还是做AP好一点

**Comment by paldier** [comment]
滚远点

**Comment by mbtCoder** [comment]
固件做后门, 现在还骂人  人品真有问题啊
