### ISSUE TITLE
Trojan节点通过订阅成功添加但无法连接

### ISSUE THREAD

**Issue by Yuhang-coder** [MerlinRdev/softcenterarm#30]
您好！

如题，trojan节点通过订阅之后添加成功，但是在连接时无论使用何种模式都无法科学上网，尝试手动添加节点也无济于事。相反的是，V2Ray节点添加之后成功连接上，效果良好。如图所示为实际效果。

感谢阅览。

![A0EE0D67-867C-4C4F-9E9C-E1A3A969FEC1](https://user-images.githubusercontent.com/72481908/95282654-7b2e2f00-088c-11eb-9b57-836d473d1058.jpeg)
![0CB0B2BC-9E14-4BFC-A644-117BCE65D2F0](https://user-images.githubusercontent.com/72481908/95282658-7ec1b600-088c-11eb-8e23-0a5b59c0be20.jpeg)

**Comment by nimasi** [comment]
请问下你这个4.3.3的是哪里下的，这里只找到4.2.8的

**Comment by nimasi** [comment]
@Yuhang-coder
请问这个版本的插件能分享一下吗
